export const item: string;
export const details: string;
export const image: string;
export const description: string;
export const actions: string;
export const price: string;
export const amountContainer: string;
export const amount: string;
export const removeButton: string;
