export enum cart {
  CART_FETCH_LOADING = 'CART_FETCH_LOADING',
  CART_FETCH_SUCCESS = 'CART_FETCH_SUCCESS',
  CART_FETCH_FAILURE = 'CART_FETCH_FAILURE',
  CART_ITEM_ADD_FETCH_LOADING = 'CART_ITEM_ADD_FETCH_LOADING',
  CART_ITEM_ADD_FETCH_SUCCESS = 'CART_ITEM_ADD_FETCH_SUCCESS',
  CART_ITEM_ADD_FETCH_FAILURE = 'CART_ITEM_ADD_FETCH_FAILURE',
  CART_ITEM_REMOVE_FETCH_LOADING = 'CART_ITEM_REMOVE_FETCH_LOADING',
  CART_ITEM_REMOVE_FETCH_SUCCESS = 'CART_ITEM_REMOVE_FETCH_SUCCESS',
  CART_ITEM_REMOVE_FETCH_FAILURE = 'CART_ITEM_REMOVE_FETCH_FAILURE',
  CART_ITEM_AMOUNT_INCREASE_FETCH_LOADING = 'CART_ITEM_AMOUNT_INCREASE_FETCH_LOADING',
  CART_ITEM_AMOUNT_INCREASE_FETCH_SUCCESS = 'CART_ITEM_AMOUNT_INCREASE_FETCH_SUCCESS',
  CART_ITEM_AMOUNT_INCREASE_FETCH_FAILURE = 'CART_ITEM_AMOUNT_INCREASE_FETCH_FAILURE',
  CART_ITEM_AMOUNT_DECREASE_FETCH_LOADING = 'CART_ITEM_AMOUNT_DECREASE_FETCH_LOADING',
  CART_ITEM_AMOUNT_DECREASE_FETCH_SUCCESS = 'CART_ITEM_AMOUNT_DECREASE_FETCH_SUCCESS',
  CART_ITEM_AMOUNT_DECREASE_FETCH_FAILURE = 'CART_ITEM_AMOUNT_DECREASE_FETCH_FAILURE'
}
